radiodjproj/account/urls.py
from django.urls import path
from django.contrib.auth import views as authviews
from account import views as accountviews

app_name = 'account'


urlpatterns = [
    # path('login/', accountviews.user_login, name='user_login'),
    path('login/', authviews.LoginView.as_view(template_name='registration/user_login.html'), name='user_login'),
    path('logout/', authviews.LogoutView.as_view(template_name='registration/user_logged_out.html'), name='user_logout'),
    path('', accountviews.dashboard, name='dashboard'),
    path('registration/', accountviews.registration_user, name='register'),
    path('editinfo/', accountviews.edit_user_info, name='edituserinfo'),
]

radiodjproj/eventgen/urls.py
from django.urls import path
from eventgen import views as eventsviews

app_name = 'eventgen'

urlpatterns = [
    # path('', eventsviews.active_events_list, name='events_list'),
    path('', eventsviews.EventsListView.as_view(), name='events_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:event>/', eventsviews.event_detail, name='event_detail'),
    path('info/', eventsviews.infopage, name='machineinfo'),

    path('<int:event_id>/share/', eventsviews.event_share_by_post, name='event_share'),
]

radiodjproj/radiodjproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.models import User

from radiodjproj import start

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', start.startpage, name='start_page'),
    path('event/', include('eventgen.urls')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls')),
]
print(settings.MEDIA_ROOT)
print(settings.MEDIA_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

radiodjproj/templates/_base_tmpl.html
{% load static %}
{% load eventgen_tags %}
<!DOCTYPE HTML>
<!-- -->
<html lang="en">
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        <link rel="stylesheet" href="{% static 'account/css/bootstrap.css' %}" />
        <link rel="stylesheet" href="{% static 'account/css/main.css' %}" />
	</head>

    <body class="is-preload homepage">

		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<header id="header" class="container">
						<!-- Logo -->
							<div id="logo">
                                {% localsystem_info as computername %}
                               <h3><a href="{% url 'start_page' %}">{{ computername.computername }}</a></h3>
                                <span>БЕЛТЕЛЕРАДИОКОМПАНИЯ</span>
{#                                <img src="/static/account/imgs/logo-bt.png" alt="">#}
							</div>
						<!-- Nav -->
							<nav id="nav">
								<ul>
									<li><a href="{% url 'eventgen:events_list' %}">События</a></li>
									<li><a href="{% url 'eventgen:machineinfo' %}">Инфо</a></li>
									{% if request.user.is_authenticated %}
                                    <li>
										<a href="#">User Profile</a>
										<ul>
{#											<li><a href="#">Lorem ipsum dolor</a></li>#}
{#											<li><a href="#">Magna phasellus</a></li>#}
{#											<li>#}
{#												<a href="#">Phasellus consequat</a>#}
{#												<ul>#}
{#													<li><a href="#">Lorem ipsum dolor</a></li>#}
{#													<li><a href="#">Phasellus consequat</a></li>#}
{#													<li><a href="#">Magna phasellus</a></li>#}
{#													<li><a href="#">Etiam dolore nisl</a></li>#}
{#												</ul>#}
{#											</li>#}
											<li><a href="{% url 'account:edituserinfo' %}">Редактировать</a></li>
											<li><a href="{% url 'account:user_logout' %}">Logout</a></li>
										</ul>
									</li>
                                    {% else %}
                                        <li data-toggle="modal" data-target="#exampleModal"><span>Log-in</span></li>
                                        <!-- Modal -->
                                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                              <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                      <h2 class="modal-title" id="exampleModalLabel">Авторизация!</h2>
                                                  </div>
                                                  <div class="modal-body">
                                                            <form action="{% url 'account:user_login' %}" method="POST">
                                                                {% csrf_token %}
                                                                <h4>Имя</h4>
                                                                <input type="text" name="username">
                                                                <h4>Пароль</h4>
                                                                <input type="password" name="password">
                                                                <input type="hidden" name="next" value="{{ next }}">
                                                                <input class="btn btn-outline-info mt-3" type="submit" value="Log in">
                                                            </form>
                                                            <a href="{% url "social:begin" "google-oauth2" %}">LogIn with Google </a>|
                                                            <a href="{% url 'account:register' %}">Регистрация</a>
                                                  </div>

            {#                                      <div class="modal-footer">#}
            {#                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
            {#                                        <button type="button" class="btn btn-primary">Save changes</button>#}
            {#                                      </div>#}
                                                </div>
                                              </div>
                                            </div>
                                    {% endif %}
{#									<li><a href="#">Left Sidebar</a></li>#}
{#									<li><a href="#">Right Sidebar</a></li>#}
{#									<li><a href="#">No Sidebar</a></li>#}
								</ul>
							</nav>


					</header>
				</div>

			<!-- Banner -->
{#				<div id="banner-wrapper">#}
{#					<div id="banner" class="box container">#}
{#						<div class="row">#}
{#							<div class="col-7 col-12-medium">#}
{#								<h2>Hi. This is Verti.</h2>#}
{#								<p>It's a free responsive site template by HTML5 UP</p>#}
{#							</div>#}
{#							<div class="col-5 col-12-medium">#}
{#								<ul>#}
{#									<li><a href="#" class="button large icon solid fa-arrow-circle-right">Ok let's go</a></li>#}
{#									<li><a href="#" class="button alt large icon solid fa-question-circle">More info</a></li>#}
{#								</ul>#}
{#							</div>#}
{#						</div>#}
{#					</div>#}
{#				</div>#}
        </div>
    <div class="">

			<!-- Features -->
				<div id="features-wrapper">
					<div class="container">
                    {% if messages %}
                    <div class="messages-container">
                        {% for msg in messages %}
                                <div class="alert alert-{% if msg.tags == "error" %}danger{% else %}{{ msg.tags }}{% endif %}">{{ msg }}</div>
                        {% endfor %}
                    </div>
                    {% endif %}
{#						<div class="row">#}
{#							<div class="col-4 col-12-medium">#}
                                {% block content %}{% endblock %}
								<!-- Box -->
{#									<section class="box feature">#}
{#										<a href="#" class="image featured"><img src="images/pic01.jpg" alt="" /></a>#}
{#										<div class="inner">#}
{#											<header>#}
{#												<h2>Put something here</h2>#}
{#												<p>Maybe here as well I think</p>#}
{#											</header>#}
{#											<p>Phasellus quam turpis, feugiat sit amet in, hendrerit in lectus. Praesent sed semper amet bibendum tristique fringilla.</p>#}
{#										</div>#}
{#									</section>#}

{#							</div>#}
{#                        </div>#}
					</div>
				</div>
    </div>

            <!-- PAGINATION -->
    {% if is_paginated %}
        {% include 'pagination.html' %}
    {% endif %}

			<!-- Footer -->
                <hr />
				<div id="footer-wrapper">
					<footer id="footer" class="container">
						<div class="d-flex justify-content-around flex-wrap">
							<div class="col-6-medium col-12-small">
								<!-- Links -->
									<section class="widget links">
										<h3>Random Stuff</h3>
										<ul class="style2">
											<li><a href="#">Etiam feugiat condimentum</a></li>
											<li><a href="#">Aliquam imperdiet suscipit odio</a></li>
										</ul>
									</section>

							</div>


							<div class="col-6-medium col-12-small">

								<!-- Contact -->
									<section class="widget contact last">
										<h3>Связаться с нами</h3>
										<ul>
											<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
											<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
											<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
											<li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
											<li><a href="#" class="icon brands fa-pinterest"><span class="label">Pinterest</span></a></li>
										</ul>
										<p>ул. Красная, 4<br />
										г. Минск, 220114<br />
										</p>
									</section>

							</div>
						</div>
                        <div class="row">
                            <div class="col-12 col-12-medium col-12-small">

								<!-- Links -->
									<section class="widget links">
{#										<h3>Мы на карте</h3>#}
                                        <div class="map-side">
                                            <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A1e034f11b6c443161895218cee43b3f33e4d96f27dac6bc4d14b4e2dcf0eb186&amp;width=100%25&amp;height=295&amp;lang=ru_RU&amp;scroll=true"></script>
{#                                            <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A1e034f11b6c443161895218cee43b3f33e4d96f27dac6bc4d14b4e2dcf0eb186&amp;source=constructor" width="100%" height="290" frameborder="0"></iframe>#}
{#                                            <div style="overflow:hidden;width: 100%;position: relative;"><iframe width="490" height="290" src="https://maps.google.com/maps?width=490&amp;height=290&amp;hl=en&amp;q=%D0%9C%D0%B8%D0%BD%D1%81%D0%BA%2C%20%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F%204+(%D0%94%D0%BE%D0%BC%20%D0%A0%D0%B0%D0%B4%D0%B8%D0%BE)&amp;ie=UTF8&amp;t=p&amp;z=16&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><div style="position: absolute;width: 80%;bottom: 10px;left: 0;right: 0;margin-left: auto;margin-right: auto;color: #000;text-align: center;"><small style="line-height: 1.8;font-size: 2px;background: #fff;">Powered by <a href="https://embedgooglemaps.com/">Embedgooglemaps.com/</a> & <a href="https://lasvegastop10restaurants.embedgooglemaps.com/">lasvegastop10restaurants</a></small></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div><br />#}
                                        </div>
{#										<ul class="style2">#}
{#											<li><a href="#">Etiam feugiat condimentum</a></li>#}
{#											<li><a href="#">Aliquam imperdiet suscipit odio</a></li>#}
{#											<li><a href="#">Sed porttitor cras in erat nec</a></li>#}
{#											<li><a href="#">Felis varius pellentesque potenti</a></li>#}
{#											<li><a href="#">Nullam scelerisque blandit leo</a></li>#}
{#										</ul>#}
									</section>

							</div>
                        </div>
						<div class="d-flex">
							<div class="col-12">
								<div id="copyright">
									<ul class="menu">
										<li>&copy; Radio 2019. All rights reserved</li><li>Design: <a href="">ДКТ</a></li>
									</ul>
								</div>
							</div>
						</div>
					</footer>
                </div>
        <script src="{% static 'account/js/jquery.min.js' %}"></script>
{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>#}
    <!-- Bootstrap js -->
        <script type="text/javascript" src="{% static 'account/js/bootstrapjs/bootstrap.js' %}"></script>
        <script type="text/javascript" src="{% static 'account/js/bootstrapjs/bootstrap.bundle.js' %}"></script>
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>#}
{#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>#}


    <!-- Scripts -->


            <script src="{% static 'account/js/jquery.dropotron.min.js' %}"></script>
            <script src="{% static 'account/js/browser.min.js' %}"></script>
            <script src="{% static 'account/js/breakpoints.min.js' %}"></script>
            <script src="{% static 'account/js/util.js' %}"></script>
            <script src="{% static 'account/js/main.js' %}"></script>
    </body>
</html>

radiodjproj/templates/pagination.html
<div class="pagination">
    <span class="step-links container">
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-dark" href="?page={{ page_obj.previous_page_number }}"><<</a>
        {% endif %}


        {% for num in page_obj.paginator.page_range %}


            {% if num == page_obj.number %}
                 <span class="btn btn-outline-dark active">{{ page_obj.number }}</span>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                <a href="?page={{ num }}" class="btn btn-outline-dark">{{ num }}</a>
            {% endif %}


        {% endfor %}


        {% if page_obj.has_next %}
            <a class="btn btn-outline-dark" href="?page={{ page_obj.next_page_number }}">>></a>
        {% endif %}
    </span>
</div>