radiodjproj/account/urls.py
from django.urls import path
from django.contrib.auth import views as authviews
from account import views as accountviews

app_name = 'account'


urlpatterns = [
    # path('login/', accountviews.user_login, name='user_login'),
    path('login/', authviews.LoginView.as_view(template_name='registration/user_login.html'), name='user_login'),
    path('logout/', authviews.LogoutView.as_view(template_name='registration/user_logged_out.html'), name='user_logout'),
    path('', accountviews.dashboard, name='dashboard'),
    path('registration/', accountviews.registration_user, name='register'),
    path('editinfo/', accountviews.edit_user_info, name='edituserinfo'),
]

radiodjproj/eventgen/urls.py
from django.urls import path
from eventgen import views as eventsviews

app_name = 'eventgen'

urlpatterns = [
    # path('', eventsviews.active_events_list, name='events_list'),
    path('', eventsviews.EventsListView.as_view(), name='events_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:event>/', eventsviews.event_detail, name='event_detail'),
    path('info/', eventsviews.infopage, name='machineinfo'),

    path('<int:event_id>/share/', eventsviews.event_share_by_post, name='event_share'),
]

radiodjproj/radiodjproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.models import User

from radiodjproj import start

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', start.startpage, name='start_page'),
    path('event/', include('eventgen.urls')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls')),
]
print(settings.MEDIA_ROOT)
print(settings.MEDIA_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

radiodjproj/eventgen/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

# TODO: create bg for head of events
# class BGForEvent(models.Model):
#     bg_name = models.CharField(max_length=100)
#     bg_img = models.ImageField(upload_to='colors/', default='df.png')
#
#     def __str__(self):
#         return f'Background {self.bg_name}'


class ActivatedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='active')

class Event(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('active', 'Active'),
    )

    title = models.CharField(max_length=250)
    slug_field = models.SlugField(max_length=250, unique_for_date='activated')
    create_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='radio_events')
    eventtext = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    activated = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    # bg_color = models.ForeignKey(BGForEvent, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ('-activated',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('eventgen:event_detail', args=[self.created.year, self.created.month, self.created.day, self.slug_field])

    objects = models.Manager()
    actived = ActivatedManager()

class Comment(models.Model):
    # TODO: next add a hidden info.
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, default='Anonymous user')
    email = models.EmailField()
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.event}'

radiodjproj/eventgen/forms.py
from django import forms
from eventgen.models import Comment


class EmailEventForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'text')

radiodjproj/eventgen/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail

from eventgen.models import Event, Comment
from eventgen.forms import EmailEventForm, CommentForm
# Create your views here.

def infopage(request):
    return render(request, 'eventgen/event/machineinfo.html')

def event_share_by_post(request, event_id):
    # Get event by index
    event = get_object_or_404(Event, id=event_id, status='active')
    sent = False
    if request.method == 'POST':
        # Form was saved
        form = EmailEventForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # ...try to send mail
            event_url = request.build_absolute_uri(event.get_absolute_url())
            subject = '{},({}) recomends you reading "{}"'.format(cd['name'], cd['email'], event.title)
            message = f'Read "{event.title}" at {event_url}\n\n{cd["name"]}\'s comments: {cd["comments"]}'
            send_mail(subject, message, 'admin@admin.tv', [cd['to']])
            sent = True
        else:
            form = EmailEventForm()
    else:
        form = EmailEventForm()
    return render(request, 'eventgen/event/eventshare.html', {'event': event, 'form': form, 'sent': sent})

class EventsListView(ListView):
    queryset = Event.actived.all()
    context_object_name = 'events'
    paginate_by = 3
    template_name = 'eventgen/event/all_active.html'

# LIKE AS EventsListView, but method

# def active_events_list(request):
#     object_list = Event.actived.all()
#     paginator = Paginator(object_list, per_page=3)
#     page = request.GET.get('page')
#     pagi = True if paginator.num_pages else False
#
#
#     try:
#         events = paginator.page(page)
#     except PageNotAnInteger:
#         events = paginator.page(1)
#     except EmptyPage:
#         events = paginator.page(paginator.num_pages)
#
#     return render(request, 'eventgen/event/all_active.html', {'activeevents': events, 'page': page, 'pagi': pagi})

def event_detail(request, year, month, day, event):
    current_event = get_object_or_404(Event, slug_field=event, status='active', activated__year=year,
                                      activated__month=month, activated__day=day)
    comments = current_event.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.event = current_event
            new_comment.save()
        else:
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    return render(request, 'eventgen/event/event_detail.html', {'event': current_event,
                                                                'comments': comments,
                                                                'new_comment': new_comment,
                                                                'comment_form': comment_form,
                                                                })

radiodjproj/eventgen/templates/eventgen/event/all_active.html
{% extends '_base_tmpl.html' %}

{% block title %}ourEvents{% endblock %}

{% block content %}
{#    {% for event in events %}#}
{#        <h2>#}
{#            <a href="{{ event.get_absolute_url }}">{{ event.title }}</a>#}
{#        </h2>#}
{#        <p class="date">Created: {{ event.activated|date:'j E Y, H:i' }} by {{ event.create_by }}</p>#}
{##}
{#        {{ event.eventtext|truncatewords:15|linebreaks }}#}
{#    {% endfor %}#}
{#    {% if is_paginated %}#}
{#        {% include 'eventgen/pagination.html' with page=event %}#}
{#    {% endif %}#}

    {% for event in events %}
    <div class="col-12 col-12-medium mb-4">
        <section class="box feature">
            <a href="#" class="image featured"><img src='' alt="PATH TO EVENT IMG" /></a>
            <div class="inner">
                <header>
                    <h3>{{ event.title }}</h3>
                    <p>{{ event.create_by }} at {{ event.created|date:"d E Y  - H:i" }}</p>
                </header>
                <p>{{ event.eventtext | truncatechars:300 }}</p>
            </div>
        </section>
    </div>
    {% endfor %}

{% endblock %}

radiodjproj/eventgen/templates/eventgen/event/event_detail.html
{% extends '_base_tmpl.html' %}

{% block title %}
{{ event.title }}
{% endblock %}

{% block content %}
<h2>{{ event.title }}</h2>
    <p class="date">Published: {{ event.created }} by {{ event.create_by }}</p>
    {{ event.eventtext|linebreaks }}

    <p><a href="{% url 'eventgen:event_share' event.id %}">Share this post</a></p>

    {% with comments.count as total_comments %}
        <h3>{{ total_comments }} comment {{ total_comments|pluralize }}</h3>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.text|linebreaks }}
        </div>
        {% empty %}
            <p>There are no comments yet...</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment:</h2>
        <form action="." method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <p><input type="submit" value="Add comment"></p>
        </form>

    {% endif %}

{% endblock %}

radiodjproj/eventgen/templates/eventgen/event/eventshare.html
{% extends '_base_tmpl.html' %}

{% block title %}
Share a event
{% endblock %}

{% block content %}
    {% if sent %}
        <h2>Email successfully sent to {{ form.cleaned_data.to }}</h2>
    {% else %}
        <h2>Share "{{ event.title }}" by email</h2>
        <form action="." method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

radiodjproj/eventgen/templates/eventgen/event/machineinfo.html
{% extends '_base_tmpl.html' %}
{% load eventgen_tags %}

{% block title %}
Machine INFO
{% endblock %}

{% block content %}
    {% localsystem_info as machineinfo %}
    {% for key, info in machineinfo.items %}
        <p>{{ key }} : {{info}}</p>
    {% endfor %}
    <p>LOGIN : {{ user }}</p>
{% endblock %}